repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [commit]
        language: python
        langauge_version: python3.11
        entry: poetry run mypy --ignore-missing-imports --no-strict-optional .
        types: [python]
        pass_filenames: false
#  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#    sha: v1.0.4
#    hooks:
#      - id: python-bandit-vulnerability-check
