repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        additional_dependencies: [flake8-typing-imports==1.6.0]
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: poetry run mypy .
        types: [python]
        pass_filenames: false
#  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
#    sha: v1.0.4
#    hooks:
#      - id: python-bandit-vulnerability-check
